spring:
  application:
    name: currency-exchange-service
  profiles:
      active: dev
  config:
    import: 'configserver:'
  zipkin:
    base-url: http://localhost:9411/
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8000